remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Kippot Shopp
description: <img alt="8b60a59c536536e215065e318f3ba0b73a370b3c-1 (1)" src="https://github.com/user-attachments/assets/cb0a1812-f032-4e65-bf74-55d464695cb3" />



show_downloads: false

